name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  APP_NAME: todo-app
  IMAGE_NAME: asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/todo-app-repo/todo-app
  NAMESPACE: todo-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: 'gke-gcloud-auth-plugin'

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet

    - name: Build and Push Docker Image
      working-directory: Cicd_Kube
      run: |
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker push $IMAGE_NAME:${{ github.sha }}
        docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest

    - name: Get GKE Credentials
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID

    - name: Apply Kubernetes Deployment
      run: |
        export USE_GKE_GCLOUD_AUTH_PLUGIN=True
        kubectl apply -f k8s/deployment.yaml -n $NAMESPACE
        kubectl rollout status deployment/$APP_NAME -n $NAMESPACE
