name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  DOCKER_REGISTRY: asia-southeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/todo-app-repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev

    - name: Build and Push Docker image
      run: |
        docker build -t $DOCKER_REGISTRY/todo-app:${{ github.sha }} .
        docker push $DOCKER_REGISTRY/todo-app:${{ github.sha }}
        docker tag $DOCKER_REGISTRY/todo-app:${{ github.sha }} $DOCKER_REGISTRY/todo-app:latest
        docker push $DOCKER_REGISTRY/todo-app:latest

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

    - name: Deploy to GKE
      run: |
        sed -i 's|image:.*|image: $DOCKER_REGISTRY/todo-app:latest|' k8s/deployment.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml 